# Generated by Django 5.1.7 on 2025-03-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_rename_participants_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='events',
            new_name='event',
        ),
    ]
